import { ROUTES } from './routes'

const HOME_ACTIVE_PAGES = new Set([
  ROUTES.HOME,
  ROUTES.LEADERBOARD,
  ROUTES.PROFILE,
  ROUTES.VICTORY,
  ROUTES.GAME,
  ROUTES.NOTIFICATIONS,
  ROUTES.SETTINGS,
  ROUTES.LEARN_HUB,
  ROUTES.TOPIC_DETAIL,
])

const THEMES_ACTIVE_PAGES = new Set([ROUTES.THEMES])

const MULTIPLAYER_ACTIVE_PAGES = new Set([
  ROUTES.MULTIPLAYER,
  ROUTES.JOIN_ROOM,
  ROUTES.CREATE_ROOM,
  ROUTES.GUEST_LOBBY,
  ROUTES.HOST_LOBBY,
  ROUTES.MULTIPLAYER_GAME,
  ROUTES.ELIMINATION_SPECTATOR,
  ROUTES.MULTIPLAYER_STANDINGS,
  ROUTES.MULTIPLAYER_REVIEW,
])

export const getNavActive = (page) => {
  if (HOME_ACTIVE_PAGES.has(page)) return ROUTES.HOME
  if (THEMES_ACTIVE_PAGES.has(page)) return ROUTES.THEMES
  if (MULTIPLAYER_ACTIVE_PAGES.has(page)) return ROUTES.MULTIPLAYER
  return null
}
