/** App page ids — match screen map where designs exist */
export const ROUTES = {
  LOGIN: 'login',
  SIGNUP: 'signup',
  HOME: 'home',
  THEMES: 'themes',
  MULTIPLAYER: 'multiplayer',
  JOIN_ROOM: 'join-room',
  CREATE_ROOM: 'create-room',
  PROFILE: 'profile',
  LEADERBOARD: 'leaderboard',
  LEARN_HUB: 'learn-hub',
  TOPIC_DETAIL: 'topic-detail',
  NOTIFICATIONS: 'notifications',
  GAME: 'game',
  SETTINGS: 'settings',
  VICTORY: 'victory',
  GUEST_LOBBY: 'guest-lobby',
  HOST_LOBBY: 'host-lobby',
  MULTIPLAYER_GAME: 'multiplayer-game',
  ELIMINATION_SPECTATOR: 'elimination-spectator',
  MULTIPLAYER_STANDINGS: 'multiplayer-standings',
  MULTIPLAYER_REVIEW: 'multiplayer-review',
}
