/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#191211',
        'surface-dim': '#191211',
        'surface-bright': '#403736',
        'surface-container-lowest': '#130d0c',
        'surface-container-low': '#211a19',
        'surface-container': '#261e1d',
        'surface-container-high': '#302827',
        'surface-container-highest': '#3c3332',
        'on-surface': '#eedfdd',
        'on-surface-variant': '#e0bfb6',
        'inverse-surface': '#eedfdd',
        'inverse-on-surface': '#372e2d',
        outline: '#a88a81',
        'outline-variant': '#59413a',
        'surface-tint': '#ffb59e',
        primary: '#ffb59e',
        'on-primary': '#5d1800',
        'primary-container': '#ef6637',
        'on-primary-container': '#521400',
        'inverse-primary': '#ab3506',
        secondary: '#f4b8b5',
        'on-secondary': '#4c2525',
        'secondary-container': '#663b3a',
        'on-secondary-container': '#e1a7a4',
        tertiary: '#ffb95c',
        'on-tertiary': '#462a00',
        'tertiary-container': '#c48320',
        'on-tertiary-container': '#3d2400',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffdbd0',
        'primary-fixed-dim': '#ffb59e',
        'on-primary-fixed': '#390b00',
        'on-primary-fixed-variant': '#842500',
        'secondary-fixed': '#ffdad8',
        'secondary-fixed-dim': '#f4b8b5',
        'on-secondary-fixed': '#321111',
        'on-secondary-fixed-variant': '#663b3a',
        'tertiary-fixed': '#ffddb7',
        'tertiary-fixed-dim': '#ffb95c',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        background: '#191211',
        'on-background': '#eedfdd',
        'surface-variant': '#3c3332',
        brand: '#ef6637',
        accent: '#ffb95c',
        dark: '#191211',
        light: '#eedfdd',
        mahogany: '#663b3a',
      },
      fontFamily: {
        serif: ['Source Serif 4', 'serif'],
        sans: ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '34px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'base': '8px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
      },
      maxWidth: {
        'container': '1280px',
      },
      boxShadow: {
        'elevation': '0 30px 60px rgba(0, 0, 0, 0.4)',
        'smooth': '0 15px 35px rgba(0, 0, 0, 0.3)',
      },
    },
  },
  plugins: [],
}
