CREATE TABLE IF NOT EXISTS "Category" (
  "CategoryId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoryCode" varchar(80) UNIQUE NOT NULL,
  "name" varchar(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS "PrizeLevel" (
  "PrizeLevelId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "prizeLevelCode" varchar(80) UNIQUE NOT NULL,
  "prizeValue" integer NOT NULL,
  "isSafetyNet" boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "Question" (
  "QuestionId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "questionCode" varchar(80) UNIQUE NOT NULL,
  "question" text NOT NULL,
  "CategoryId" integer NOT NULL,
  "PrizeLevelId" integer NOT NULL,
  "isActive" boolean NOT NULL DEFAULT true,
  CONSTRAINT fk_question_category
    FOREIGN KEY ("CategoryId") REFERENCES "Category" ("CategoryId")
    ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_question_prize_level
    FOREIGN KEY ("PrizeLevelId") REFERENCES "PrizeLevel" ("PrizeLevelId")
    ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS "Answer" (
  "AnswerId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "answerCode" varchar(80) UNIQUE NOT NULL,
  "answer" text NOT NULL,
  "QuestionId" integer NOT NULL,
  "isCorrect" boolean NOT NULL DEFAULT false,
  "justification" text,
  CONSTRAINT fk_answer_question
    FOREIGN KEY ("QuestionId") REFERENCES "Question" ("QuestionId")
    ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS "PhoneAPeerHint" (
  "PhoneAPeerHintId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phoneAPeerHintCode" varchar(80) UNIQUE NOT NULL,
  "QuestionId" integer NOT NULL,
  "avatarName" varchar(120) NOT NULL,
  "hintText" text NOT NULL,
  "isActive" boolean NOT NULL DEFAULT true,
  CONSTRAINT fk_phone_hint_question
    FOREIGN KEY ("QuestionId") REFERENCES "Question" ("QuestionId")
    ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS "CourseNoteHint" (
  "CourseNoteHintId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courseNoteHintCode" varchar(80) UNIQUE NOT NULL,
  "QuestionId" integer NOT NULL,
  "noteText" text NOT NULL,
  "isActive" boolean NOT NULL DEFAULT true,
  CONSTRAINT fk_course_hint_question
    FOREIGN KEY ("QuestionId") REFERENCES "Question" ("QuestionId")
    ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS "Player" (
  "PlayerId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "playerCode" varchar(80) UNIQUE NOT NULL,
  "username" varchar(80) UNIQUE NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "passwordHash" text NOT NULL,
  "name" varchar(150) NOT NULL,
  "isActive" boolean NOT NULL DEFAULT true,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "Game" (
  "GameId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gameCode" varchar(80) UNIQUE NOT NULL,
  "player1" integer NOT NULL,
  "player2" integer,
  "player3" integer,
  "player4" integer,
  "winner" integer,
  "status" varchar(20) NOT NULL DEFAULT 'waiting',
  "gameMode" varchar(50) NOT NULL DEFAULT 'Real-Time Speed',
  "timeLimit" integer NOT NULL DEFAULT 45,
  "maxPlayers" integer NOT NULL DEFAULT 4,
  "startTime" timestamptz DEFAULT now(),
  "endTime" timestamptz,
  CONSTRAINT fk_game_player1 FOREIGN KEY ("player1") REFERENCES "Player" ("PlayerId") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_game_player2 FOREIGN KEY ("player2") REFERENCES "Player" ("PlayerId") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_game_player3 FOREIGN KEY ("player3") REFERENCES "Player" ("PlayerId") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_game_player4 FOREIGN KEY ("player4") REFERENCES "Player" ("PlayerId") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_game_winner FOREIGN KEY ("winner") REFERENCES "Player" ("PlayerId") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT chk_game_status CHECK ("status" IN ('waiting', 'active', 'completed', 'abandoned'))
);

CREATE TABLE IF NOT EXISTS "PlayerGameLifeline" (
  "PlayerGameLifelineId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PlayerId" integer NOT NULL,
  "GameId" integer NOT NULL,
  "lifeLineAskClass" boolean NOT NULL DEFAULT true,
  "lifeLineAskClassResult" text,
  "lifeLine5050" boolean NOT NULL DEFAULT true,
  "lifeLinePhone" boolean NOT NULL DEFAULT true,
  "lifeLinePhoneResult" integer,
  "lifeLineNotes" boolean NOT NULL DEFAULT true,
  "lifeLineNotesResult" integer,
  CONSTRAINT fk_pgl_player FOREIGN KEY ("PlayerId") REFERENCES "Player" ("PlayerId") ON DELETE CASCADE,
  CONSTRAINT fk_pgl_game FOREIGN KEY ("GameId") REFERENCES "Game" ("GameId") ON DELETE CASCADE,
  CONSTRAINT fk_pgl_phone_hint FOREIGN KEY ("lifeLinePhoneResult") REFERENCES "PhoneAPeerHint" ("PhoneAPeerHintId") ON DELETE SET NULL,
  CONSTRAINT fk_pgl_note_hint FOREIGN KEY ("lifeLineNotesResult") REFERENCES "CourseNoteHint" ("CourseNoteHintId") ON DELETE SET NULL,
  CONSTRAINT uq_player_game_lifeline UNIQUE ("PlayerId", "GameId")
);

CREATE TABLE IF NOT EXISTS "Notification" (
  "NotificationId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PlayerId" integer NOT NULL,
  "title" varchar(150) NOT NULL,
  "message" text NOT NULL,
  "type" varchar(50) NOT NULL,
  "isRead" boolean NOT NULL DEFAULT false,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "linkRoute" varchar(100),
  CONSTRAINT fk_notification_player FOREIGN KEY ("PlayerId") REFERENCES "Player" ("PlayerId") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Achievement" (
  "AchievementId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) UNIQUE NOT NULL,
  "description" text NOT NULL,
  "icon" varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "PlayerAchievement" (
  "PlayerAchievementId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PlayerId" integer NOT NULL,
  "AchievementId" integer NOT NULL,
  "unlockedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_pa_player FOREIGN KEY ("PlayerId") REFERENCES "Player" ("PlayerId") ON DELETE CASCADE,
  CONSTRAINT fk_pa_achievement FOREIGN KEY ("AchievementId") REFERENCES "Achievement" ("AchievementId") ON DELETE CASCADE,
  CONSTRAINT uq_player_achievement UNIQUE ("PlayerId", "AchievementId")
);

CREATE TABLE IF NOT EXISTS "PlayerSettings" (
  "PlayerId" integer PRIMARY KEY REFERENCES "Player" ("PlayerId") ON DELETE CASCADE,
  "allowSpeedInvites" boolean NOT NULL DEFAULT true,
  "themePreference" varchar(50) NOT NULL DEFAULT 'Heritage Earth',
  "volumeLevel" integer NOT NULL DEFAULT 85
);

CREATE TABLE IF NOT EXISTS "GameCategory" (
  "GameCategoryId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gameCategoryCode" varchar(80) UNIQUE NOT NULL,
  "GameId" integer NOT NULL,
  "CategoryId" integer NOT NULL,
  CONSTRAINT fk_game_category_game FOREIGN KEY ("GameId") REFERENCES "Game" ("GameId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_game_category_category FOREIGN KEY ("CategoryId") REFERENCES "Category" ("CategoryId") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT uq_game_category UNIQUE ("GameId", "CategoryId")
);

CREATE TABLE IF NOT EXISTS "PlayerGameAnswer" (
  "PlayerGameAnswerId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "playerGameAnswerCode" varchar(80) UNIQUE NOT NULL,
  "GameId" integer NOT NULL,
  "PlayerId" integer NOT NULL,
  "QuestionId" integer NOT NULL,
  "AnswerId" integer NOT NULL,
  "isCorrect" boolean NOT NULL,
  "questionSequence" integer NOT NULL,
  "answeredAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_pga_game FOREIGN KEY ("GameId") REFERENCES "Game" ("GameId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_pga_player FOREIGN KEY ("PlayerId") REFERENCES "Player" ("PlayerId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_pga_question FOREIGN KEY ("QuestionId") REFERENCES "Question" ("QuestionId") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_pga_answer FOREIGN KEY ("AnswerId") REFERENCES "Answer" ("AnswerId") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT uq_pga_question UNIQUE ("GameId", "PlayerId", "QuestionId")
);

CREATE TABLE IF NOT EXISTS "AskTheClassVote" (
  "VoteId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "voteCode" varchar(80) UNIQUE NOT NULL,
  "GameId" integer NOT NULL,
  "QuestionId" integer NOT NULL,
  "AnswerId" integer NOT NULL,
  "PlayerId" integer NOT NULL,
  "votedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_vote_game FOREIGN KEY ("GameId") REFERENCES "Game" ("GameId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_vote_question FOREIGN KEY ("QuestionId") REFERENCES "Question" ("QuestionId") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_vote_answer FOREIGN KEY ("AnswerId") REFERENCES "Answer" ("AnswerId") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_vote_player FOREIGN KEY ("PlayerId") REFERENCES "Player" ("PlayerId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT uq_vote_once UNIQUE ("GameId", "QuestionId", "PlayerId")
);

CREATE TABLE IF NOT EXISTS "Leaderboard" (
  "LeaderboardId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PlayerId" integer NOT NULL UNIQUE,
  "totalGames" integer NOT NULL DEFAULT 0,
  "totalWins" integer NOT NULL DEFAULT 0,
  "totalCorrect" integer NOT NULL DEFAULT 0,
  "bestScore" integer NOT NULL DEFAULT 0,
  "rank" integer NOT NULL DEFAULT 0,
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_leaderboard_player FOREIGN KEY ("PlayerId") REFERENCES "Player" ("PlayerId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE INDEX IF NOT EXISTS idx_question_category_prize ON "Question" ("CategoryId", "PrizeLevelId");
CREATE INDEX IF NOT EXISTS idx_pga_game_player ON "PlayerGameAnswer" ("GameId", "PlayerId");
CREATE INDEX IF NOT EXISTS idx_vote_game_question ON "AskTheClassVote" ("GameId", "QuestionId");
