"""add auth fields, AskTheClassVote and Leaderboard

Revision ID: bf8cb38fc3db
Revises: a9a5a10ebda0
Create Date: 2026-06-01 08:52:26.405663
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8cb38fc3db'
down_revision: Union[str, None] = 'a9a5a10ebda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Leaderboard',
    sa.Column('LeaderboardId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PlayerId', sa.Integer(), nullable=False),
    sa.Column('totalGames', sa.Integer(), nullable=False),
    sa.Column('totalWins', sa.Integer(), nullable=False),
    sa.Column('totalCorrect', sa.Integer(), nullable=False),
    sa.Column('bestScore', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['PlayerId'], ['Player.PlayerId'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('LeaderboardId'),
    sa.UniqueConstraint('PlayerId')
    )
    op.create_table('AskTheClassVote',
    sa.Column('VoteId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voteCode', sa.String(), nullable=False),
    sa.Column('GameId', sa.Integer(), nullable=False),
    sa.Column('QuestionId', sa.Integer(), nullable=False),
    sa.Column('AnswerId', sa.Integer(), nullable=False),
    sa.Column('PlayerId', sa.Integer(), nullable=False),
    sa.Column('votedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['AnswerId'], ['Answer.AnswerId'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['GameId'], ['Game.GameId'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['PlayerId'], ['Player.PlayerId'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['QuestionId'], ['Question.QuestionId'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('VoteId'),
    sa.UniqueConstraint('voteCode')
    )
    with op.batch_alter_table('Player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('passwordHash', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('isActive', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('isActive')
        batch_op.drop_column('passwordHash')
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    op.drop_table('AskTheClassVote')
    op.drop_table('Leaderboard')
    # ### end Alembic commands ###
