"""initial schema from Leonard design

Revision ID: a9a5a10ebda0
Revises: 
Create Date: 2026-05-31 17:23:53.891644
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a5a10ebda0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('CategoryId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoryCode', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('CategoryId'),
    sa.UniqueConstraint('categoryCode')
    )
    op.create_table('PrizeLevel',
    sa.Column('PrizeLevelId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prizeLevelCode', sa.String(), nullable=False),
    sa.Column('prizeValue', sa.Integer(), nullable=False),
    sa.Column('isSafetyNet', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('PrizeLevelId'),
    sa.UniqueConstraint('prizeLevelCode')
    )
    op.create_table('Question',
    sa.Column('QuestionId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('questionCode', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('CategoryId', sa.Integer(), nullable=False),
    sa.Column('PrizeLevelId', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['CategoryId'], ['Category.CategoryId'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['PrizeLevelId'], ['PrizeLevel.PrizeLevelId'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('QuestionId'),
    sa.UniqueConstraint('questionCode')
    )
    op.create_table('Answer',
    sa.Column('AnswerId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answerCode', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('QuestionId', sa.Integer(), nullable=False),
    sa.Column('isCorrect', sa.Boolean(), nullable=False),
    sa.Column('justification', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['QuestionId'], ['Question.QuestionId'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('AnswerId'),
    sa.UniqueConstraint('answerCode')
    )
    op.create_table('CourseNoteHint',
    sa.Column('CourseNoteHintId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('courseNoteHintCode', sa.String(), nullable=False),
    sa.Column('QuestionId', sa.Integer(), nullable=False),
    sa.Column('noteText', sa.String(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['QuestionId'], ['Question.QuestionId'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('CourseNoteHintId'),
    sa.UniqueConstraint('courseNoteHintCode')
    )
    op.create_table('PhoneAPeerHint',
    sa.Column('PhoneAPeerHintId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phoneAPeerHintCode', sa.String(), nullable=False),
    sa.Column('QuestionId', sa.Integer(), nullable=False),
    sa.Column('avatarName', sa.String(), nullable=False),
    sa.Column('hintText', sa.String(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['QuestionId'], ['Question.QuestionId'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('PhoneAPeerHintId'),
    sa.UniqueConstraint('phoneAPeerHintCode')
    )
    op.create_table('Player',
    sa.Column('PlayerId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playerCode', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lifeLineAskClass', sa.Boolean(), nullable=False),
    sa.Column('lifeLineAskClassResult', sa.String(), nullable=True),
    sa.Column('lifeLine5050', sa.Boolean(), nullable=False),
    sa.Column('lifeLinePhone', sa.Boolean(), nullable=False),
    sa.Column('lifeLinePhoneResult', sa.Integer(), nullable=True),
    sa.Column('lifeLineNotes', sa.Boolean(), nullable=False),
    sa.Column('lifeLineNotesResult', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lifeLineNotesResult'], ['CourseNoteHint.CourseNoteHintId'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['lifeLinePhoneResult'], ['PhoneAPeerHint.PhoneAPeerHintId'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('PlayerId'),
    sa.UniqueConstraint('playerCode')
    )
    op.create_table('Game',
    sa.Column('GameId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gameCode', sa.String(), nullable=False),
    sa.Column('player1', sa.Integer(), nullable=False),
    sa.Column('player2', sa.Integer(), nullable=True),
    sa.Column('player3', sa.Integer(), nullable=True),
    sa.Column('player4', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('startTime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('endTime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player1'], ['Player.PlayerId'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['player2'], ['Player.PlayerId'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['player3'], ['Player.PlayerId'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['player4'], ['Player.PlayerId'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['winner'], ['Player.PlayerId'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('GameId'),
    sa.UniqueConstraint('gameCode')
    )
    op.create_table('GameCategory',
    sa.Column('GameCategoryId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gameCategoryCode', sa.String(), nullable=False),
    sa.Column('GameId', sa.Integer(), nullable=False),
    sa.Column('CategoryId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CategoryId'], ['Category.CategoryId'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['GameId'], ['Game.GameId'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('GameCategoryId'),
    sa.UniqueConstraint('gameCategoryCode')
    )
    op.create_table('PlayerGameAnswer',
    sa.Column('PlayerGameAnswerId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playerGameAnswerCode', sa.String(), nullable=False),
    sa.Column('GameId', sa.Integer(), nullable=False),
    sa.Column('PlayerId', sa.Integer(), nullable=False),
    sa.Column('QuestionId', sa.Integer(), nullable=False),
    sa.Column('AnswerId', sa.Integer(), nullable=False),
    sa.Column('isCorrect', sa.Boolean(), nullable=False),
    sa.Column('questionSequence', sa.Integer(), nullable=False),
    sa.Column('answeredAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['AnswerId'], ['Answer.AnswerId'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['GameId'], ['Game.GameId'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['PlayerId'], ['Player.PlayerId'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['QuestionId'], ['Question.QuestionId'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('PlayerGameAnswerId'),
    sa.UniqueConstraint('playerGameAnswerCode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PlayerGameAnswer')
    op.drop_table('GameCategory')
    op.drop_table('Game')
    op.drop_table('Player')
    op.drop_table('PhoneAPeerHint')
    op.drop_table('CourseNoteHint')
    op.drop_table('Answer')
    op.drop_table('Question')
    op.drop_table('PrizeLevel')
    op.drop_table('Category')
    # ### end Alembic commands ###
