ALTER TABLE "Question" ADD FOREIGN KEY ("CategoryId") REFERENCES "Category" ("CategoryId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Question" ADD FOREIGN KEY ("PrizeLevelId") REFERENCES "PrizeLevel" ("PrizeLevelId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Answer" ADD FOREIGN KEY ("QuestionId") REFERENCES "Question" ("QuestionId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PhoneAPeerHint" ADD FOREIGN KEY ("QuestionId") REFERENCES "Question" ("QuestionId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CourseNoteHint" ADD FOREIGN KEY ("QuestionId") REFERENCES "Question" ("QuestionId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Player" ADD FOREIGN KEY ("lifeLinePhoneResult") REFERENCES "PhoneAPeerHint" ("PhoneAPeerHintId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Player" ADD FOREIGN KEY ("lifeLineNotesResult") REFERENCES "CourseNoteHint" ("CourseNoteHintId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Game" ADD FOREIGN KEY ("player1") REFERENCES "Player" ("PlayerId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Game" ADD FOREIGN KEY ("player2") REFERENCES "Player" ("PlayerId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Game" ADD FOREIGN KEY ("player3") REFERENCES "Player" ("PlayerId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Game" ADD FOREIGN KEY ("player4") REFERENCES "Player" ("PlayerId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Game" ADD FOREIGN KEY ("winner") REFERENCES "Player" ("PlayerId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "GameCategory" ADD FOREIGN KEY ("GameId") REFERENCES "Game" ("GameId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "GameCategory" ADD FOREIGN KEY ("CategoryId") REFERENCES "Category" ("CategoryId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PlayerGameAnswer" ADD FOREIGN KEY ("GameId") REFERENCES "Game" ("GameId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PlayerGameAnswer" ADD FOREIGN KEY ("PlayerId") REFERENCES "Player" ("PlayerId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PlayerGameAnswer" ADD FOREIGN KEY ("QuestionId") REFERENCES "Question" ("QuestionId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PlayerGameAnswer" ADD FOREIGN KEY ("AnswerId") REFERENCES "Answer" ("AnswerId") DEFERRABLE INITIALLY IMMEDIATE;
